# Generated by Django 5.0.7 on 2024-07-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_validate',
            field=models.BooleanField(),
        ),
    ]
